from mu_plus_lambda_EA import retrieve_value_one_plus_one_ea
from mu_plus_lambda_GA import retrieve_value_mu_plus_lambda_ga
from one_plus_mu_lambda_GA import retrieve_value_one_plus_mu_lambda_adaptive_ga, retrieve_value_one_plus_mu_lambda_ga
from exhaustive_search import retrieve_value_exhaustive_search
from erdos_renyi import retrieve_value_erdos_renyi

number_of_colors = [pow(2, i) for i in range(9)]

retrieve_value_one_plus_one_ea(number_of_colors)
retrieve_value_mu_plus_lambda_ga(2, 1, 2, number_of_colors)
retrieve_value_mu_plus_lambda_ga(10, 6, 5, number_of_colors)
retrieve_value_one_plus_mu_lambda_ga(4, number_of_colors)
retrieve_value_one_plus_mu_lambda_ga(8, number_of_colors)
retrieve_value_one_plus_mu_lambda_ga(12, number_of_colors)
retrieve_value_one_plus_mu_lambda_adaptive_ga(4, 1.1, number_of_colors)
retrieve_value_exhaustive_search(number_of_colors)
retrieve_value_erdos_renyi(number_of_colors)
